services:
    ibot-gpt:
        image: 'ghcr.io/slendymilky/ibot-modo:2.0.4'
        container_name: ibot-modo
        restart: always
        env_file:
            - stack.env
        volumes:
            - bot_db:/iBot-Modo/database

volumes:
  bot_db: {}